// This file is generated by omniidl (C++ backend) - omniORB_4_1. Do not edit.

#include "DataPort.hh"

OMNI_USING_NAMESPACE(omni)

static const char* _0RL_dyn_library_version = omniORB_4_1_dyn;

static ::CORBA::TypeCode::_Tracker _0RL_tcTrack(__FILE__);

static const char* _0RL_enumMember_OpenRTM_mPortStatus[] = { "PORT_OK", "PORT_ERROR", "BUFFER_FULL", "BUFFER_EMPTY", "BUFFER_TIMEOUT", "UNKNOWN_ERROR" };
static CORBA::TypeCode_ptr _0RL_tc_OpenRTM_mPortStatus = CORBA::TypeCode::PR_enum_tc("IDL:OpenRTM/PortStatus:1.0", "PortStatus", _0RL_enumMember_OpenRTM_mPortStatus, 6, &_0RL_tcTrack);
#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace OpenRTM { 
  const ::CORBA::TypeCode_ptr _tc_PortStatus = _0RL_tc_OpenRTM_mPortStatus;
} 
#else
const ::CORBA::TypeCode_ptr OpenRTM::_tc_PortStatus = _0RL_tc_OpenRTM_mPortStatus;
#endif

static CORBA::TypeCode_ptr _0RL_tc_OpenRTM_mCdrData = CORBA::TypeCode::PR_alias_tc("IDL:OpenRTM/CdrData:1.0", "CdrData", CORBA::TypeCode::PR_sequence_tc(0, CORBA::TypeCode::PR_octet_tc(), &_0RL_tcTrack), &_0RL_tcTrack);


#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace OpenRTM { 
  const ::CORBA::TypeCode_ptr _tc_CdrData = _0RL_tc_OpenRTM_mCdrData;
} 
#else
const ::CORBA::TypeCode_ptr OpenRTM::_tc_CdrData = _0RL_tc_OpenRTM_mCdrData;
#endif

#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace OpenRTM { 
  const ::CORBA::TypeCode_ptr _tc_InPortCdr = CORBA::TypeCode::PR_interface_tc("IDL:OpenRTM/InPortCdr:1.0", "InPortCdr", &_0RL_tcTrack);
} 
#else
const ::CORBA::TypeCode_ptr OpenRTM::_tc_InPortCdr = CORBA::TypeCode::PR_interface_tc("IDL:OpenRTM/InPortCdr:1.0", "InPortCdr", &_0RL_tcTrack);
#endif

#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace OpenRTM { 
  const ::CORBA::TypeCode_ptr _tc_OutPortCdr = CORBA::TypeCode::PR_interface_tc("IDL:OpenRTM/OutPortCdr:1.0", "OutPortCdr", &_0RL_tcTrack);
} 
#else
const ::CORBA::TypeCode_ptr OpenRTM::_tc_OutPortCdr = CORBA::TypeCode::PR_interface_tc("IDL:OpenRTM/OutPortCdr:1.0", "OutPortCdr", &_0RL_tcTrack);
#endif

static void _0RL_OpenRTM_mPortStatus_marshal_fn(cdrStream& _s, void* _v)
{
  OpenRTM::PortStatus* _p = (OpenRTM::PortStatus*)_v;
  *_p >>= _s;
}
static void _0RL_OpenRTM_mPortStatus_unmarshal_fn(cdrStream& _s, void*& _v)
{
  OpenRTM::PortStatus* _p = (OpenRTM::PortStatus*)_v;
  *_p <<= _s;
}

void operator<<=(::CORBA::Any& _a, OpenRTM::PortStatus _s)
{
  _a.PR_insert(_0RL_tc_OpenRTM_mPortStatus,
               _0RL_OpenRTM_mPortStatus_marshal_fn,
               &_s);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, OpenRTM::PortStatus& _s)
{
  return _a.PR_extract(_0RL_tc_OpenRTM_mPortStatus,
                       _0RL_OpenRTM_mPortStatus_unmarshal_fn,
                       &_s);
}

static void _0RL_OpenRTM_mCdrData_marshal_fn(cdrStream& _s, void* _v)
{
  OpenRTM::CdrData* _p = (OpenRTM::CdrData*)_v;
  *_p >>= _s;
}
static void _0RL_OpenRTM_mCdrData_unmarshal_fn(cdrStream& _s, void*& _v)
{
  OpenRTM::CdrData* _p = new OpenRTM::CdrData;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_OpenRTM_mCdrData_destructor_fn(void* _v)
{
  OpenRTM::CdrData* _p = (OpenRTM::CdrData*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const OpenRTM::CdrData& _s)
{
  OpenRTM::CdrData* _p = new OpenRTM::CdrData(_s);
  _a.PR_insert(_0RL_tc_OpenRTM_mCdrData,
               _0RL_OpenRTM_mCdrData_marshal_fn,
               _0RL_OpenRTM_mCdrData_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, OpenRTM::CdrData* _sp)
{
  _a.PR_insert(_0RL_tc_OpenRTM_mCdrData,
               _0RL_OpenRTM_mCdrData_marshal_fn,
               _0RL_OpenRTM_mCdrData_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, OpenRTM::CdrData*& _sp)
{
  return _a >>= (const OpenRTM::CdrData*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const OpenRTM::CdrData*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_OpenRTM_mCdrData,
                    _0RL_OpenRTM_mCdrData_unmarshal_fn,
                    _0RL_OpenRTM_mCdrData_marshal_fn,
                    _0RL_OpenRTM_mCdrData_destructor_fn,
                    _v)) {
    _sp = (const OpenRTM::CdrData*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_OpenRTM_mInPortCdr_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_OpenRTM_mInPortCdr_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(OpenRTM::InPortCdr::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_OpenRTM_mInPortCdr_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, OpenRTM::InPortCdr_ptr _o)
{
  OpenRTM::InPortCdr_ptr _no = OpenRTM::InPortCdr::_duplicate(_o);
  _a.PR_insert(OpenRTM::_tc_InPortCdr,
               _0RL_OpenRTM_mInPortCdr_marshal_fn,
               _0RL_OpenRTM_mInPortCdr_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, OpenRTM::InPortCdr_ptr* _op)
{
  _a.PR_insert(OpenRTM::_tc_InPortCdr,
               _0RL_OpenRTM_mInPortCdr_marshal_fn,
               _0RL_OpenRTM_mInPortCdr_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = OpenRTM::InPortCdr::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, OpenRTM::InPortCdr_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(OpenRTM::_tc_InPortCdr,
                    _0RL_OpenRTM_mInPortCdr_unmarshal_fn,
                    _0RL_OpenRTM_mInPortCdr_marshal_fn,
                    _0RL_OpenRTM_mInPortCdr_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (OpenRTM::InPortCdr_ptr)_r->_ptrToObjRef(OpenRTM::InPortCdr::_PD_repoId);
    else
      _o = OpenRTM::InPortCdr::_nil();
    return 1;
  }
  return 0;
}

static void _0RL_OpenRTM_mOutPortCdr_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_OpenRTM_mOutPortCdr_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(OpenRTM::OutPortCdr::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_OpenRTM_mOutPortCdr_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, OpenRTM::OutPortCdr_ptr _o)
{
  OpenRTM::OutPortCdr_ptr _no = OpenRTM::OutPortCdr::_duplicate(_o);
  _a.PR_insert(OpenRTM::_tc_OutPortCdr,
               _0RL_OpenRTM_mOutPortCdr_marshal_fn,
               _0RL_OpenRTM_mOutPortCdr_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, OpenRTM::OutPortCdr_ptr* _op)
{
  _a.PR_insert(OpenRTM::_tc_OutPortCdr,
               _0RL_OpenRTM_mOutPortCdr_marshal_fn,
               _0RL_OpenRTM_mOutPortCdr_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = OpenRTM::OutPortCdr::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, OpenRTM::OutPortCdr_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(OpenRTM::_tc_OutPortCdr,
                    _0RL_OpenRTM_mOutPortCdr_unmarshal_fn,
                    _0RL_OpenRTM_mOutPortCdr_marshal_fn,
                    _0RL_OpenRTM_mOutPortCdr_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (OpenRTM::OutPortCdr_ptr)_r->_ptrToObjRef(OpenRTM::OutPortCdr::_PD_repoId);
    else
      _o = OpenRTM::OutPortCdr::_nil();
    return 1;
  }
  return 0;
}

