// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "Manager.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



void
RTM::ModuleProfile::operator>>= (cdrStream &_n) const
{
  (const NVList&) properties >>= _n;

}

void
RTM::ModuleProfile::operator<<= (cdrStream &_n)
{
  (NVList&)properties <<= _n;

}

void
RTM::ManagerProfile::operator>>= (cdrStream &_n) const
{
  (const NVList&) properties >>= _n;

}

void
RTM::ManagerProfile::operator<<= (cdrStream &_n)
{
  (NVList&)properties <<= _n;

}

RTM::Manager_ptr RTM::Manager_Helper::_nil() {
  return ::RTM::Manager::_nil();
}

::CORBA::Boolean RTM::Manager_Helper::is_nil(::RTM::Manager_ptr p) {
  return ::CORBA::is_nil(p);

}

void RTM::Manager_Helper::release(::RTM::Manager_ptr p) {
  ::CORBA::release(p);
}

void RTM::Manager_Helper::marshalObjRef(::RTM::Manager_ptr obj, cdrStream& s) {
  ::RTM::Manager::_marshalObjRef(obj, s);
}

RTM::Manager_ptr RTM::Manager_Helper::unmarshalObjRef(cdrStream& s) {
  return ::RTM::Manager::_unmarshalObjRef(s);
}

void RTM::Manager_Helper::duplicate(::RTM::Manager_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

RTM::Manager_ptr
RTM::Manager::_duplicate(::RTM::Manager_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

RTM::Manager_ptr
RTM::Manager::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


RTM::Manager_ptr
RTM::Manager::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

RTM::Manager_ptr
RTM::Manager::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Manager _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Manager* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_Manager;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* RTM::Manager::_PD_repoId = "IDL:RTM/Manager:1.0";


RTM::_objref_Manager::~_objref_Manager() {
  
}


RTM::_objref_Manager::_objref_Manager(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::RTM::Manager::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
RTM::_objref_Manager::_ptrToObjRef(const char* id)
{
  if( id == ::RTM::Manager::_PD_repoId )
    return (::RTM::Manager_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::RTM::Manager::_PD_repoId) )
    return (::RTM::Manager_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mReturnCode__t_i_cstring_i_cstring
class _0RL_cd_f30e1745ea13c2d7_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_f30e1745ea13c2d7_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  RTC::ReturnCode_t result;
};

void _0RL_cd_f30e1745ea13c2d7_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);

}

void _0RL_cd_f30e1745ea13c2d7_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();

}

void _0RL_cd_f30e1745ea13c2d7_00000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_f30e1745ea13c2d7_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (RTC::ReturnCode_t&)result <<= _n;

}

const char* const _0RL_cd_f30e1745ea13c2d7_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_00000000* tcd = (_0RL_cd_f30e1745ea13c2d7_00000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->load_module(tcd->arg_0, tcd->arg_1);


}

RTC::ReturnCode_t RTM::_objref_Manager::load_module(const char* pathname, const char* initfunc)
{
  _0RL_cd_f30e1745ea13c2d7_00000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_10000000, "load_module", 12);
  _call_desc.arg_0 = pathname;
  _call_desc.arg_1 = initfunc;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cRTC_mReturnCode__t_i_cstring
class _0RL_cd_f30e1745ea13c2d7_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_f30e1745ea13c2d7_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  RTC::ReturnCode_t result;
};

void _0RL_cd_f30e1745ea13c2d7_20000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_f30e1745ea13c2d7_20000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_f30e1745ea13c2d7_20000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_f30e1745ea13c2d7_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  (RTC::ReturnCode_t&)result <<= _n;

}

const char* const _0RL_cd_f30e1745ea13c2d7_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_20000000* tcd = (_0RL_cd_f30e1745ea13c2d7_20000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->unload_module(tcd->arg_0);


}

RTC::ReturnCode_t RTM::_objref_Manager::unload_module(const char* pathname)
{
  _0RL_cd_f30e1745ea13c2d7_20000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_30000000, "unload_module", 14);
  _call_desc.arg_0 = pathname;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cRTM_mModuleProfileList
class _0RL_cd_f30e1745ea13c2d7_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_f30e1745ea13c2d7_40000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTM::ModuleProfileList_var result;
};

void _0RL_cd_f30e1745ea13c2d7_40000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTM::ModuleProfileList&) result >>= _n;

}

void _0RL_cd_f30e1745ea13c2d7_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTM::ModuleProfileList;
  (RTM::ModuleProfileList&)result <<= _n;

}

const char* const _0RL_cd_f30e1745ea13c2d7_40000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_40000000* tcd = (_0RL_cd_f30e1745ea13c2d7_40000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->get_loadable_modules();


}

RTM::ModuleProfileList* RTM::_objref_Manager::get_loadable_modules()
{
  _0RL_cd_f30e1745ea13c2d7_40000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_50000000, "get_loadable_modules", 21);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_60000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_40000000* tcd = (_0RL_cd_f30e1745ea13c2d7_40000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->get_loaded_modules();


}

RTM::ModuleProfileList* RTM::_objref_Manager::get_loaded_modules()
{
  _0RL_cd_f30e1745ea13c2d7_40000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_60000000, "get_loaded_modules", 19);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_70000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_40000000* tcd = (_0RL_cd_f30e1745ea13c2d7_40000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->get_factory_profiles();


}

RTM::ModuleProfileList* RTM::_objref_Manager::get_factory_profiles()
{
  _0RL_cd_f30e1745ea13c2d7_40000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_70000000, "get_factory_profiles", 21);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRTObject_i_cstring
class _0RL_cd_f30e1745ea13c2d7_80000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_f30e1745ea13c2d7_80000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  RTC::RTObject_var result;
};

void _0RL_cd_f30e1745ea13c2d7_80000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_f30e1745ea13c2d7_80000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_f30e1745ea13c2d7_80000000::marshalReturnedValues(cdrStream& _n)
{
  RTC::RTObject_Helper::marshalObjRef(result,_n);

}

void _0RL_cd_f30e1745ea13c2d7_80000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = RTC::RTObject_Helper::unmarshalObjRef(_n);

}

const char* const _0RL_cd_f30e1745ea13c2d7_80000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_90000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_80000000* tcd = (_0RL_cd_f30e1745ea13c2d7_80000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->create_component(tcd->arg_0);


}

RTC::RTObject_ptr RTM::_objref_Manager::create_component(const char* module_name)
{
  _0RL_cd_f30e1745ea13c2d7_80000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_90000000, "create_component", 17);
  _call_desc.arg_0 = module_name;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_a0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_20000000* tcd = (_0RL_cd_f30e1745ea13c2d7_20000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->delete_component(tcd->arg_0);


}

RTC::ReturnCode_t RTM::_objref_Manager::delete_component(const char* instance_name)
{
  _0RL_cd_f30e1745ea13c2d7_20000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_a0000000, "delete_component", 17);
  _call_desc.arg_0 = instance_name;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRTCList
class _0RL_cd_f30e1745ea13c2d7_b0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_f30e1745ea13c2d7_b0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::RTCList_var result;
};

void _0RL_cd_f30e1745ea13c2d7_b0000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RTCList&) result >>= _n;

}

void _0RL_cd_f30e1745ea13c2d7_b0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RTCList;
  (RTC::RTCList&)result <<= _n;

}

const char* const _0RL_cd_f30e1745ea13c2d7_b0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_c0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_b0000000* tcd = (_0RL_cd_f30e1745ea13c2d7_b0000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->get_components();


}

RTC::RTCList* RTM::_objref_Manager::get_components()
{
  _0RL_cd_f30e1745ea13c2d7_b0000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_c0000000, "get_components", 15);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cRTC_mComponentProfileList
class _0RL_cd_f30e1745ea13c2d7_d0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_f30e1745ea13c2d7_d0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::ComponentProfileList_var result;
};

void _0RL_cd_f30e1745ea13c2d7_d0000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::ComponentProfileList&) result >>= _n;

}

void _0RL_cd_f30e1745ea13c2d7_d0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::ComponentProfileList;
  (RTC::ComponentProfileList&)result <<= _n;

}

const char* const _0RL_cd_f30e1745ea13c2d7_d0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_e0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_d0000000* tcd = (_0RL_cd_f30e1745ea13c2d7_d0000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->get_component_profiles();


}

RTC::ComponentProfileList* RTM::_objref_Manager::get_component_profiles()
{
  _0RL_cd_f30e1745ea13c2d7_d0000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_e0000000, "get_component_profiles", 23);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cRTM_mManagerProfile
class _0RL_cd_f30e1745ea13c2d7_f0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_f30e1745ea13c2d7_f0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTM::ManagerProfile_var result;
};

void _0RL_cd_f30e1745ea13c2d7_f0000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTM::ManagerProfile&) result >>= _n;

}

void _0RL_cd_f30e1745ea13c2d7_f0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTM::ManagerProfile;
  (RTM::ManagerProfile&)result <<= _n;

}

const char* const _0RL_cd_f30e1745ea13c2d7_f0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_01000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_f0000000* tcd = (_0RL_cd_f30e1745ea13c2d7_f0000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->get_profile();


}

RTM::ManagerProfile* RTM::_objref_Manager::get_profile()
{
  _0RL_cd_f30e1745ea13c2d7_f0000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_01000000, "get_profile", 12);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cSDOPackage_mNVList
class _0RL_cd_f30e1745ea13c2d7_11000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_f30e1745ea13c2d7_11000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTM::NVList_var result;
};

void _0RL_cd_f30e1745ea13c2d7_11000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTM::NVList&) result >>= _n;

}

void _0RL_cd_f30e1745ea13c2d7_11000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTM::NVList;
  (RTM::NVList&)result <<= _n;

}

const char* const _0RL_cd_f30e1745ea13c2d7_11000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_21000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_11000000* tcd = (_0RL_cd_f30e1745ea13c2d7_11000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->get_configuration();


}

RTM::NVList* RTM::_objref_Manager::get_configuration()
{
  _0RL_cd_f30e1745ea13c2d7_11000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_21000000, "get_configuration", 18);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_31000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_00000000* tcd = (_0RL_cd_f30e1745ea13c2d7_00000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->set_configuration(tcd->arg_0, tcd->arg_1);


}

RTC::ReturnCode_t RTM::_objref_Manager::set_configuration(const char* name, const char* value)
{
  _0RL_cd_f30e1745ea13c2d7_00000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_31000000, "set_configuration", 18);
  _call_desc.arg_0 = name;
  _call_desc.arg_1 = value;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean
class _0RL_cd_f30e1745ea13c2d7_41000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_f30e1745ea13c2d7_41000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Boolean result;
};

void _0RL_cd_f30e1745ea13c2d7_41000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_f30e1745ea13c2d7_41000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_f30e1745ea13c2d7_41000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_51000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_41000000* tcd = (_0RL_cd_f30e1745ea13c2d7_41000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->is_master();


}

::CORBA::Boolean RTM::_objref_Manager::is_master()
{
  _0RL_cd_f30e1745ea13c2d7_41000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_51000000, "is_master", 10);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cRTM_mManagerList
class _0RL_cd_f30e1745ea13c2d7_61000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_f30e1745ea13c2d7_61000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTM::ManagerList_var result;
};

void _0RL_cd_f30e1745ea13c2d7_61000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTM::ManagerList&) result >>= _n;

}

void _0RL_cd_f30e1745ea13c2d7_61000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTM::ManagerList;
  (RTM::ManagerList&)result <<= _n;

}

const char* const _0RL_cd_f30e1745ea13c2d7_61000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_71000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_61000000* tcd = (_0RL_cd_f30e1745ea13c2d7_61000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->get_master_managers();


}

RTM::ManagerList* RTM::_objref_Manager::get_master_managers()
{
  _0RL_cd_f30e1745ea13c2d7_61000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_71000000, "get_master_managers", 20);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cRTC_mReturnCode__t_i_cRTM_mManager
class _0RL_cd_f30e1745ea13c2d7_81000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_f30e1745ea13c2d7_81000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTM::Manager_var arg_0_;
  RTM::Manager_ptr arg_0;
  RTC::ReturnCode_t result;
};

void _0RL_cd_f30e1745ea13c2d7_81000000::marshalArguments(cdrStream& _n)
{
  RTM::Manager_Helper::marshalObjRef(arg_0,_n);

}

void _0RL_cd_f30e1745ea13c2d7_81000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = RTM::Manager_Helper::unmarshalObjRef(_n);
  arg_0 = arg_0_.in();

}

void _0RL_cd_f30e1745ea13c2d7_81000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_f30e1745ea13c2d7_81000000::unmarshalReturnedValues(cdrStream& _n)
{
  (RTC::ReturnCode_t&)result <<= _n;

}

const char* const _0RL_cd_f30e1745ea13c2d7_81000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_91000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_81000000* tcd = (_0RL_cd_f30e1745ea13c2d7_81000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->add_master_manager(tcd->arg_0);


}

RTC::ReturnCode_t RTM::_objref_Manager::add_master_manager(::RTM::Manager_ptr mgr)
{
  _0RL_cd_f30e1745ea13c2d7_81000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_91000000, "add_master_manager", 19);
  _call_desc.arg_0 = mgr;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_a1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_81000000* tcd = (_0RL_cd_f30e1745ea13c2d7_81000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->remove_master_manager(tcd->arg_0);


}

RTC::ReturnCode_t RTM::_objref_Manager::remove_master_manager(::RTM::Manager_ptr mgr)
{
  _0RL_cd_f30e1745ea13c2d7_81000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_a1000000, "remove_master_manager", 22);
  _call_desc.arg_0 = mgr;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_b1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_61000000* tcd = (_0RL_cd_f30e1745ea13c2d7_61000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->get_slave_managers();


}

RTM::ManagerList* RTM::_objref_Manager::get_slave_managers()
{
  _0RL_cd_f30e1745ea13c2d7_61000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_b1000000, "get_slave_managers", 19);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_c1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_81000000* tcd = (_0RL_cd_f30e1745ea13c2d7_81000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->add_slave_manager(tcd->arg_0);


}

RTC::ReturnCode_t RTM::_objref_Manager::add_slave_manager(::RTM::Manager_ptr mgr)
{
  _0RL_cd_f30e1745ea13c2d7_81000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_c1000000, "add_slave_manager", 18);
  _call_desc.arg_0 = mgr;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_d1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_81000000* tcd = (_0RL_cd_f30e1745ea13c2d7_81000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->remove_slave_manager(tcd->arg_0);


}

RTC::ReturnCode_t RTM::_objref_Manager::remove_slave_manager(::RTM::Manager_ptr mgr)
{
  _0RL_cd_f30e1745ea13c2d7_81000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_d1000000, "remove_slave_manager", 21);
  _call_desc.arg_0 = mgr;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cRTC_mReturnCode__t
class _0RL_cd_f30e1745ea13c2d7_e1000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_f30e1745ea13c2d7_e1000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::ReturnCode_t result;
};

void _0RL_cd_f30e1745ea13c2d7_e1000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_f30e1745ea13c2d7_e1000000::unmarshalReturnedValues(cdrStream& _n)
{
  (RTC::ReturnCode_t&)result <<= _n;

}

const char* const _0RL_cd_f30e1745ea13c2d7_e1000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_f1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_e1000000* tcd = (_0RL_cd_f30e1745ea13c2d7_e1000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->fork();


}

RTC::ReturnCode_t RTM::_objref_Manager::fork()
{
  _0RL_cd_f30e1745ea13c2d7_e1000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_f1000000, "fork", 5);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_02000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_e1000000* tcd = (_0RL_cd_f30e1745ea13c2d7_e1000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->shutdown();


}

RTC::ReturnCode_t RTM::_objref_Manager::shutdown()
{
  _0RL_cd_f30e1745ea13c2d7_e1000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_02000000, "shutdown", 9);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_12000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_e1000000* tcd = (_0RL_cd_f30e1745ea13c2d7_e1000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->restart();


}

RTC::ReturnCode_t RTM::_objref_Manager::restart()
{
  _0RL_cd_f30e1745ea13c2d7_e1000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_12000000, "restart", 8);


  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cCORBA_mObject_i_cstring
class _0RL_cd_f30e1745ea13c2d7_22000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_f30e1745ea13c2d7_22000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  CORBA::Object_var result;
};

void _0RL_cd_f30e1745ea13c2d7_22000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_f30e1745ea13c2d7_22000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_f30e1745ea13c2d7_22000000::marshalReturnedValues(cdrStream& _n)
{
  CORBA::Object::_marshalObjRef(result,_n);

}

void _0RL_cd_f30e1745ea13c2d7_22000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = CORBA::Object::_unmarshalObjRef(_n);

}

const char* const _0RL_cd_f30e1745ea13c2d7_22000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_f30e1745ea13c2d7_32000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_f30e1745ea13c2d7_22000000* tcd = (_0RL_cd_f30e1745ea13c2d7_22000000*)cd;
  RTM::_impl_Manager* impl = (RTM::_impl_Manager*) svnt->_ptrToInterface(RTM::Manager::_PD_repoId);
  tcd->result = impl->get_service(tcd->arg_0);


}

CORBA::Object_ptr RTM::_objref_Manager::get_service(const char* name)
{
  _0RL_cd_f30e1745ea13c2d7_22000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_32000000, "get_service", 12);
  _call_desc.arg_0 = name;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
RTM::_pof_Manager::~_pof_Manager() {}


omniObjRef*
RTM::_pof_Manager::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::RTM::_objref_Manager(ior, id);
}


::CORBA::Boolean
RTM::_pof_Manager::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::RTM::Manager::_PD_repoId) )
    return 1;
  
  return 0;
}

const RTM::_pof_Manager _the_pof_RTM_mManager;

RTM::_impl_Manager::~_impl_Manager() {}


::CORBA::Boolean
RTM::_impl_Manager::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "load_module") ) {

    _0RL_cd_f30e1745ea13c2d7_00000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_10000000, "load_module", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "unload_module") ) {

    _0RL_cd_f30e1745ea13c2d7_20000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_30000000, "unload_module", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_loadable_modules") ) {

    _0RL_cd_f30e1745ea13c2d7_40000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_50000000, "get_loadable_modules", 21, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_loaded_modules") ) {

    _0RL_cd_f30e1745ea13c2d7_40000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_60000000, "get_loaded_modules", 19, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_factory_profiles") ) {

    _0RL_cd_f30e1745ea13c2d7_40000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_70000000, "get_factory_profiles", 21, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "create_component") ) {

    _0RL_cd_f30e1745ea13c2d7_80000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_90000000, "create_component", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "delete_component") ) {

    _0RL_cd_f30e1745ea13c2d7_20000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_a0000000, "delete_component", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_components") ) {

    _0RL_cd_f30e1745ea13c2d7_b0000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_c0000000, "get_components", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_component_profiles") ) {

    _0RL_cd_f30e1745ea13c2d7_d0000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_e0000000, "get_component_profiles", 23, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_profile") ) {

    _0RL_cd_f30e1745ea13c2d7_f0000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_01000000, "get_profile", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_configuration") ) {

    _0RL_cd_f30e1745ea13c2d7_11000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_21000000, "get_configuration", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "set_configuration") ) {

    _0RL_cd_f30e1745ea13c2d7_00000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_31000000, "set_configuration", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "is_master") ) {

    _0RL_cd_f30e1745ea13c2d7_41000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_51000000, "is_master", 10, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_master_managers") ) {

    _0RL_cd_f30e1745ea13c2d7_61000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_71000000, "get_master_managers", 20, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "add_master_manager") ) {

    _0RL_cd_f30e1745ea13c2d7_81000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_91000000, "add_master_manager", 19, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "remove_master_manager") ) {

    _0RL_cd_f30e1745ea13c2d7_81000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_a1000000, "remove_master_manager", 22, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_slave_managers") ) {

    _0RL_cd_f30e1745ea13c2d7_61000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_b1000000, "get_slave_managers", 19, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "add_slave_manager") ) {

    _0RL_cd_f30e1745ea13c2d7_81000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_c1000000, "add_slave_manager", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "remove_slave_manager") ) {

    _0RL_cd_f30e1745ea13c2d7_81000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_d1000000, "remove_slave_manager", 21, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "fork") ) {

    _0RL_cd_f30e1745ea13c2d7_e1000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_f1000000, "fork", 5, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "shutdown") ) {

    _0RL_cd_f30e1745ea13c2d7_e1000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_02000000, "shutdown", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "restart") ) {

    _0RL_cd_f30e1745ea13c2d7_e1000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_12000000, "restart", 8, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_service") ) {

    _0RL_cd_f30e1745ea13c2d7_22000000 _call_desc(_0RL_lcfn_f30e1745ea13c2d7_32000000, "get_service", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
RTM::_impl_Manager::_ptrToInterface(const char* id)
{
  if( id == ::RTM::Manager::_PD_repoId )
    return (::RTM::_impl_Manager*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::RTM::Manager::_PD_repoId) )
    return (::RTM::_impl_Manager*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
RTM::_impl_Manager::_mostDerivedRepoId()
{
  return ::RTM::Manager::_PD_repoId;
}

POA_RTM::Manager::~Manager() {}

